on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - v*
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: WordPress Plugin SVN Deploy
        uses: nk-o/action-wordpress-plugin-deploy@v0.0.5
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: bookster-search-form
